### ISSUE TITLE
Margin between logo and plus button too small on my device 

### ISSUE THREAD

**Issue by stdx** [amarradi/palatschinkencounter#8]
![signal-2022-02-06-215038](https://user-images.githubusercontent.com/238151/152700815-0e6abfb7-7126-4852-93b3-320e3b6a6f16.png)

**Comment by amarradi** [comment]
Thanks for reporting the bug. We will take care of it as soon as possible. We hope you have a great experience with the Pancake counter.
Estimated version for fixing the bug is version 1.0.6
