### ISSUE TITLE
Delete the last pancake

### ISSUE THREAD

**Issue by amarradi** [amarradi/palatschinkencounter#9]
I want to delete the last pancake again in case I accidentally pressed plus once too often. Everything should happen without asking or warning and without extra confirmation

**Comment by Label** [comment]
I'd suggest implementing a circular menu on a longer tap on the  +1 button. In the circular menu there is place for more buttons for future features. The first feature could be a -1 button.
Alternatively one could implement a swipe up mechanism on the +1 button to convert it into a -1 feature.

**Comment by amarradi** [comment]
My first idea was to implement a hidden feature.  The user should simply long on the current state of the eaten pancakes and then a pancake is deducted. No confirmation and no information. Swipe right is plus and swipe left is minus is also pretty cool.

**Comment by amarradi** [comment]
Now you can reset the complete counter by long tabbing the counter. Why should I reduce the counter? Either I ate the pancake or not
